### ISSUE TITLE
Looks like the nordugrid repo install on a clean machine will fail

### ISSUE THREAD

**Issue by rob-c** [uki-scotgrid-glasgow/ansible#1]
https://github.com/uki-scotgrid-glasgow/ansible/blob/7e4af7146214a4f5cd6d0743b3c56f9ffeb87cb9/roles/repo-nordugrid-6/tasks/main.yml#L20

Just having a play with github while I wait for ansible to re-run but I think the .rpmnew test here is un-needed and may fail on a clean host which has never installed nordugrid before. (at least it did for me)

**Comment by gpstewart** [comment]
Fixed in 5099c26: unnecessary reference to .rpmnew file removed.
